apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: k812c54lh-nodejs-gitops
  description: This is GitOps manifest for k812c54lh-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=k812c54lh-nodejs
    backstage.io/kubernetes-id: k812c54lh-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: k812c54lh-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:k812c54lh-nodejs
