apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k812c54lh-nodejs
  janus-idp.io/tekton: k812c54lh-nodejs
  backstage.io/kubernetes-id: k812c54lh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k812c54lh-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
